name: Build-sphinx-docs-and-deploy

on:
  # Triggers the workflow on push request events
  push:
    branches: 
      - 'main'

  workflow_dispatch:

jobs: 
  build: 
    runs-on: [self-hosted, solinas]

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
           python-version: "3.10"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    

      - name: Generate Sphinx docs
        run: |
          chmod +x generate_docs.sh
          echo Running documentation creation script
          ./generate_docs.sh

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html
